In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

!pip install --no-deps d2l
import torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.7/111.7 kB 2.4 MB/s eta 0:00:00a 0:00:01


## 2.1 数据操作
- 核心数据类型：张量`tensor`
  - 一个由数值组成的n维数组；
  - 一维张量又称向量`vector`，二维张量又称为矩阵`matrix`

### 2.1.1 基础

In [2]:
## 基础属性及创建方式

x = torch.arange(12)
print(f"x形如\n{x}\n")

## 查看形状
print(f"x的形状为\n{x.shape}\n")

## 查看总长度
print(f"x的元素总数为\n{x.numel()}")

x形如
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

x的形状为
torch.Size([12])

x的元素总数为
12


In [3]:
## 改变张量形状
X = x.reshape(3, 4)

### 维度的自动计算机制 
X_1 = x.reshape(-1, 4) 
X_2 = x.reshape(3, -1)
X, X_1, X_2
### 结果一致

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [4]:
## 使用其他函数初始化张量
print(f"初始化零值张量：\n{torch.zeros((3, 4, 5))}\n")

print(f"初始化值为1的张量：\n{torch.ones((3, 4, 5))}\n")

print(f"使用标准正态分布进行初始化的张量：\n{torch.randn((3, 4))}\n")

print(f"自定义数值创建张量：\n{torch.tensor([[2, 1, 3, 4], [1, 2, 3, 4], [1, 3, 4, 2]])}")

初始化零值张量：
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

初始化值为1的张量：
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

使用标准正态分布进行初始化的张量：
tensor([[ 0.2351, -0.2575,  0.7261, -0.3820],
        [-1.3620, -1.2738,  1.1819,  0.9838],
        [ 0.5716, -0.8544, -0.0158,  0.9256]])

自定义数值创建张量：
tensor([[2, 1, 3, 4],
        [1, 2, 3, 4],
        [

## 2.1.2 运算符
两个形状相同的张量**按元素**进行运算，包括：
- 加法 `+`
- 减法 `-`
- 乘法 `*`
- 除法 `/`
- 幂运算 `**`
- 自然常数幂 $ e ^ x $ 

In [5]:
x = torch.tensor([1.2, 3, 6, 8])
y = torch.tensor([2, 1, 3, 4])
x + y, x - y, x * y, x / y, x ** y, torch.exp(x)

(tensor([ 3.2000,  4.0000,  9.0000, 12.0000]),
 tensor([-0.8000,  2.0000,  3.0000,  4.0000]),
 tensor([ 2.4000,  3.0000, 18.0000, 32.0000]),
 tensor([0.6000, 3.0000, 2.0000, 2.0000]),
 tensor([1.4400e+00, 3.0000e+00, 2.1600e+02, 4.0960e+03]),
 tensor([   3.3201,   20.0855,  403.4288, 2980.9580]))

#### 其他常见的运算：
- 点积（dot） `·`
- 矩阵乘法
- 逻辑运算
- 求和、平均

In [6]:
##
### 点积
X = torch

### 2.3.x 矩阵范数 `norm`
#### a) 含义和作用：
 - 使用一个标量数值表征一个矩阵的大小/长度
#### b) 性质：
 - 非负性：
 - 齐次性：
 - 三角不等式：
#### 常见的范数:
 - $L_1$ 范数：$\| x \| _1 = \sum_{i=1}^{n}|x_i| $  `近似于曼哈顿距离` 
 - $L_2$ 范数：$\| x \| _2 = \sqrt{\sum_{i=1}^{n}x_i^2} $ `近似于欧式距离`
 - $L_p$ 范数：$\| x \| _p = ({\sum_{i=1}^{n}|x_i|^p})^{1/p} $ `一般情况，L1、L2范数是其特殊形式`
 - $弗罗贝尼乌斯$ 范数：$\| x \| _f = \sqrt{{\sum_{i=1}^{m}}{\sum_{j=1}^{n}}|x_{ij}^2|} $ `矩阵语境下的L2范数：对每个矩阵的元素加权计算平方和后开方，以下简称弗式范数`

In [13]:
u = torch.tensor([3.0, 4.0, 7.0 ,1.0]) 

## 常见范数的实现
### L1范数
normL1 = torch.abs(u).sum()
print(f"张量u的L1范数为：{normL1}")

### L2范数
normL2 = (u ** 2).sum().sqrt() 
print(f"张量u的L2范数为：{normL2}")

#### 等价操作
print(f"张量u的L2范数为：{torch.norm(u)}")

### 弗式范数
matrix = torch.arange(12, dtype=torch.float).reshape(3, 4)
matrix[0, 0] = 3

print(f"矩阵matrix的弗式范数为：{torch.norm(matrix)}")
print(f"矩阵matrix的弗式范数为：{}")

张量u的L1范数为：15.0
张量u的L2范数为：8.66025447845459
张量u的L2范数为：8.66025447845459
矩阵matrix的弗式范数为：22.69361114501953
